set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)

set(TOOLCHAIN_PREFIX "/opt/gcc-arm-none-eabi-10.3-2021.10/bin/")
set(CMAKE_SYSROOT "/opt/gcc-arm-none-eabi-10.3-2021.10")

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}arm-none-eabi-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}arm-none-eabi-gcc)
set(CMAKE_LINKER ${TOOLCHAIN_PREFIX}arm-none-eabi-ld)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
